# Puedes personalizar los colores para que coincidan con los de tu logo
[theme]

#primaryColor = "#FFCD4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#305AA0"
textColor = "#262730"
font = "sans serif"
