# Puedes personalizar los colores para que coincidan con los de tu logo
[theme]

primaryColor = "#004DFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
